echo Assembling kasm.asm...
nasm -f elf32 kernel.asm -o kasm.o
echo Assembling kernel.c...
gcc -m32 -c kernel.c -o kc.o
echo Linking kernel...
ld -m elf_i386 -T linker.ld -o znix/boot/kernel.bin kasm.o kc.o
rm kasm.o kc.o
echo Building image...
grub-mkrescue -o znix.iso znix
echo Launching VM...
qemu-system-i386 -kernel znix/boot/kernel.bin